[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ocean-carbon"
authors = [{name = "Elsworth", email = "genevieve.elsworth@gmail.com"}]
dynamic = ["version", "description"]
